#!/bin/sh
#
# chkconfig: - 86 14
# description: logSquid server daemon
# processname: logsquid_server
# config: /usr/local/etc/logSquid/logsquid_server.conf
#

### BEGIN INIT INFO
# Provides: logsquid_server
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start:
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: Start and stop logSquid server
# Description: logSquid server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

if [ -x /usr/local/bin/logsquid_server ]; then
    exec=/usr/local/bin/logsquid_server
else
    exit 5
fi

prog=${exec##*/}
conf=/usr/local/etc/logSquid/logsquid_server.conf
pidfile=$(grep -e "^PidFile=.*$" $conf | cut -d= -f2)
timeout=10

if [ -f /etc/sysconfig/logsquid_server ]; then
    . /etc/sysconfig/logsquid_server
fi

lockfile=/var/lock/subsys/logsquid_server

start()
{
    echo -n $"Starting logSquid server: "
    daemon $exec -c $conf
    rv=$?
    echo
    [ $rv -eq 0 ] && touch $lockfile
    return $rv
}

stop()
{
    echo -n $"Shutting down logSquid server: "
    killproc -p $pidfile -d $timeout $prog
    rv=$?
    echo
    [ $rv -eq 0 ] && rm -f $lockfile
    return $rv
}

restart()
{
    stop
    start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    force-reload)
        restart
        ;;
    status)
        status -p $pidfile $prog 
        ;;
    try-restart|condrestart)
        if status $prog >/dev/null ; then
            restart
        fi
        ;;
    reload)
        action $"Service ${0##*/} does not support the reload action: " /bin/false
        exit 3
        ;;
    *)
	echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
	exit 2
	;;
esac

